# Generated by Django 3.0.6 on 2020-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('car', models.ManyToManyField(to='cars.Car')),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='cars_proper_name_9c9042_idx'),
        ),
    ]
