# Generated by Django 3.0.6 on 2020-06-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200611_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.RemoveField(
            model_name='property',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='order',
            field=models.ManyToManyField(to='cars.Order'),
        ),
        migrations.AddField(
            model_name='car',
            name='prop',
            field=models.ManyToManyField(to='cars.Property'),
        ),
    ]
