# Generated by Django 3.0.6 on 2020-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200612_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='order',
        ),
        migrations.RemoveField(
            model_name='car',
            name='prop',
        ),
        migrations.AddField(
            model_name='property',
            name='car',
            field=models.ManyToManyField(to='cars.Car'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
