# Generated by Django 3.0.7 on 2020-06-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_approve', 'Can approve')]},
        ),
    ]
