# Generated by Django 3.0.6 on 2020-06-12 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20200611_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Dealer', 'verbose_name_plural': 'Dealers'},
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='title',
        ),
    ]
